// Code generated by wit-bindgen-go. DO NOT EDIT.

package driver

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "openlist:plugin-driver@0.1.0".

//go:wasmimport $root log
//go:noescape
func wasmimport_Log(level0 uint32, message0 *uint8, message1 uint32)

//go:wasmimport $root load-config
//go:noescape
func wasmimport_LoadConfig(driver0 uint32, result *cm.Result[cm.List[uint8], cm.List[uint8], string])

//go:wasmimport $root save-config
//go:noescape
func wasmimport_SaveConfig(driver0 uint32, config0 *uint8, config1 uint32, result *cm.Result[string, struct{}, string])
