// Code generated by wit-bindgen-go. DO NOT EDIT.

package types

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// DriverErrorsShape is used for storage in variant or result types.
type DriverErrorsShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(DriverErrors{})]byte
}

func lower_OptionU64(v cm.Option[uint64]) (f0 uint32, f1 uint64) {
	some := v.Some()
	if some != nil {
		f0 = 1
		v1 := (uint64)(*some)
		f1 = (uint64)(v1)
	}
	return
}

// LinkInfoShape is used for storage in variant or result types.
type LinkInfoShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(LinkInfo{})]byte
}
