// Code generated by wit-bindgen-go. DO NOT EDIT.

package types

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "openlist:plugin-driver@0.1.0".

//go:wasmimport openlist:plugin-driver/types@0.1.0 [resource-drop]readable
//go:noescape
func wasmimport_ReadableResourceDrop(self0 uint32)

//go:wasmimport openlist:plugin-driver/types@0.1.0 [method]readable.get-hasher
//go:noescape
func wasmimport_ReadableGetHasher(self0 uint32, hashs0 *HashAlg, hashs1 uint32, result *cm.Result[cm.List[HashInfo], cm.List[HashInfo], string])

//go:wasmimport openlist:plugin-driver/types@0.1.0 [method]readable.peek
//go:noescape
func wasmimport_ReadablePeek(self0 uint32, offset0 uint64, len0 uint64, result *cm.Result[string, InputStream, string])

//go:wasmimport openlist:plugin-driver/types@0.1.0 [method]readable.range
//go:noescape
func wasmimport_ReadableRange(self0 uint32, offset0 uint64, len0 uint64, result *cm.Result[string, InputStream, string])

//go:wasmimport openlist:plugin-driver/types@0.1.0 [method]readable.streams
//go:noescape
func wasmimport_ReadableStreams(self0 uint32, result *cm.Result[string, InputStream, string])

//go:wasmimport openlist:plugin-driver/types@0.1.0 [method]readable.update-progress
//go:noescape
func wasmimport_ReadableUpdateProgress(self0 uint32, progress0 float64)

//go:wasmimport openlist:plugin-driver/types@0.1.0 [resource-drop]cancellable
//go:noescape
func wasmimport_CancellableResourceDrop(self0 uint32)

//go:wasmimport openlist:plugin-driver/types@0.1.0 [method]cancellable.subscribe
//go:noescape
func wasmimport_CancellableSubscribe(self0 uint32) (result0 uint32)
