// Code generated by wit-bindgen-go. DO NOT EDIT.

package exports

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// OptionObjectShape is used for storage in variant or result types.
type OptionObjectShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(cm.Option[Object]{})]byte
}

// ObjectShape is used for storage in variant or result types.
type ObjectShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Object{})]byte
}

// LinkResultShape is used for storage in variant or result types.
type LinkResultShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(LinkResult{})]byte
}

// DriverErrorsShape is used for storage in variant or result types.
type DriverErrorsShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(DriverErrors{})]byte
}
