// Code generated by wit-bindgen-go. DO NOT EDIT.

package exports

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "openlist:plugin-driver@0.1.0".

//go:wasmimport [export]openlist:plugin-driver/exports@0.1.0 [resource-new]driver
//go:noescape
func wasmimport_DriverResourceNew(rep0 uint32) (result0 uint32)

//go:wasmimport [export]openlist:plugin-driver/exports@0.1.0 [resource-rep]driver
//go:noescape
func wasmimport_DriverResourceRep(self0 uint32) (result0 uint32)

//go:wasmimport [export]openlist:plugin-driver/exports@0.1.0 [resource-drop]driver
//go:noescape
func wasmimport_DriverResourceDrop(self0 uint32)

//go:wasmexport openlist:plugin-driver/exports@0.1.0#[dtor]driver
//export openlist:plugin-driver/exports@0.1.0#[dtor]driver
func wasmexport_DriverDestructor(self0 uint32) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	Exports.Driver.Destructor(self)
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#[constructor]driver
//export openlist:plugin-driver/exports@0.1.0#[constructor]driver
func wasmexport_Constructor() (result0 uint32) {
	result := Exports.Driver.Constructor()
	result0 = cm.Reinterpret[uint32](result)
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#[method]driver.copy-file
//export openlist:plugin-driver/exports@0.1.0#[method]driver.copy-file
func wasmexport_DriverCopyFile(params *wasmexport_DriverCopyFile_params) (result *cm.Result[OptionObjectShape, cm.Option[Object], DriverErrors]) {
	result_ := Exports.Driver.CopyFile(params.self, params.ctx, params.file, params.toDir)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#[method]driver.drop
//export openlist:plugin-driver/exports@0.1.0#[method]driver.drop
func wasmexport_DriverDrop(self0 uint32, ctx0 uint32) (result *cm.Result[DriverErrors, struct{}, DriverErrors]) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	ctx := cm.Reinterpret[cm.Rep]((uint32)(ctx0))
	result_ := Exports.Driver.Drop(self, ctx)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#[method]driver.get-file
//export openlist:plugin-driver/exports@0.1.0#[method]driver.get-file
func wasmexport_DriverGetFile(self0 uint32, ctx0 uint32, path0 *uint8, path1 uint32) (result *cm.Result[ObjectShape, Object, DriverErrors]) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	ctx := cm.Reinterpret[cm.Rep]((uint32)(ctx0))
	path := cm.LiftString[string]((*uint8)(path0), (uint32)(path1))
	result_ := Exports.Driver.GetFile(self, ctx, path)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#[method]driver.get-form-meta
//export openlist:plugin-driver/exports@0.1.0#[method]driver.get-form-meta
func wasmexport_DriverGetFormMeta(self0 uint32) (result *cm.List[FormField]) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	result_ := Exports.Driver.GetFormMeta(self)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#[method]driver.get-properties
//export openlist:plugin-driver/exports@0.1.0#[method]driver.get-properties
func wasmexport_DriverGetProperties(self0 uint32) (result *DriverProps) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	result_ := Exports.Driver.GetProperties(self)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#[method]driver.get-root
//export openlist:plugin-driver/exports@0.1.0#[method]driver.get-root
func wasmexport_DriverGetRoot(self0 uint32, ctx0 uint32) (result *cm.Result[ObjectShape, Object, DriverErrors]) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	ctx := cm.Reinterpret[cm.Rep]((uint32)(ctx0))
	result_ := Exports.Driver.GetRoot(self, ctx)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#[method]driver.init
//export openlist:plugin-driver/exports@0.1.0#[method]driver.init
func wasmexport_DriverInit(self0 uint32, ctx0 uint32) (result *cm.Result[DriverErrors, struct{}, DriverErrors]) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	ctx := cm.Reinterpret[cm.Rep]((uint32)(ctx0))
	result_ := Exports.Driver.Init(self, ctx)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#[method]driver.link-file
//export openlist:plugin-driver/exports@0.1.0#[method]driver.link-file
func wasmexport_DriverLinkFile(params *wasmexport_DriverLinkFile_params) (result *cm.Result[LinkResultShape, LinkResult, DriverErrors]) {
	result_ := Exports.Driver.LinkFile(params.self, params.ctx, params.file, params.args)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#[method]driver.link-range
//export openlist:plugin-driver/exports@0.1.0#[method]driver.link-range
func wasmexport_DriverLinkRange(params *wasmexport_DriverLinkRange_params) (result *cm.Result[DriverErrors, struct{}, DriverErrors]) {
	result_ := Exports.Driver.LinkRange(params.self, params.ctx, params.file, params.args, params.range_)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#[method]driver.list-files
//export openlist:plugin-driver/exports@0.1.0#[method]driver.list-files
func wasmexport_DriverListFiles(params *wasmexport_DriverListFiles_params) (result *cm.Result[DriverErrorsShape, cm.List[Object], DriverErrors]) {
	result_ := Exports.Driver.ListFiles(params.self, params.ctx, params.dir)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#[method]driver.make-dir
//export openlist:plugin-driver/exports@0.1.0#[method]driver.make-dir
func wasmexport_DriverMakeDir(params *wasmexport_DriverMakeDir_params) (result *cm.Result[OptionObjectShape, cm.Option[Object], DriverErrors]) {
	result_ := Exports.Driver.MakeDir(params.self, params.ctx, params.dir, params.name)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#[method]driver.move-file
//export openlist:plugin-driver/exports@0.1.0#[method]driver.move-file
func wasmexport_DriverMoveFile(params *wasmexport_DriverMoveFile_params) (result *cm.Result[OptionObjectShape, cm.Option[Object], DriverErrors]) {
	result_ := Exports.Driver.MoveFile(params.self, params.ctx, params.file, params.toDir)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#[method]driver.remove-file
//export openlist:plugin-driver/exports@0.1.0#[method]driver.remove-file
func wasmexport_DriverRemoveFile(params *wasmexport_DriverRemoveFile_params) (result *cm.Result[DriverErrors, struct{}, DriverErrors]) {
	result_ := Exports.Driver.RemoveFile(params.self, params.ctx, params.file)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#[method]driver.rename-file
//export openlist:plugin-driver/exports@0.1.0#[method]driver.rename-file
func wasmexport_DriverRenameFile(params *wasmexport_DriverRenameFile_params) (result *cm.Result[OptionObjectShape, cm.Option[Object], DriverErrors]) {
	result_ := Exports.Driver.RenameFile(params.self, params.ctx, params.file, params.newName)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#[method]driver.upload-file
//export openlist:plugin-driver/exports@0.1.0#[method]driver.upload-file
func wasmexport_DriverUploadFile(params *wasmexport_DriverUploadFile_params) (result *cm.Result[OptionObjectShape, cm.Option[Object], DriverErrors]) {
	result_ := Exports.Driver.UploadFile(params.self, params.ctx, params.dir, params.req)
	result = &result_
	return
}
