// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package exports represents the exported interface "openlist:plugin-driver/exports@0.1.0".
//
// -----------------------------
// 驱动（Driver）接口
// -----------------------------
// 所有驱动插件必须实现并导出的核心接口。
// 所有 ctx 使用 borrow<cancellable> 由host端管理生命周期
package exports

import (
	"github.com/OpenListTeam/openlist-wasi-plugin-driver/binding/openlist/plugin-driver/types"
	"go.bytecodealliance.org/cm"
)

// Cancellable represents the exported type alias "openlist:plugin-driver/exports@0.1.0#cancellable".
//
// See [types.Cancellable] for more information.
type Cancellable = types.Cancellable

// DriverProps represents the type alias "openlist:plugin-driver/exports@0.1.0#driver-props".
//
// See [types.DriverProps] for more information.
type DriverProps = types.DriverProps

// FormField represents the type alias "openlist:plugin-driver/exports@0.1.0#form-field".
//
// See [types.FormField] for more information.
type FormField = types.FormField

// Capability represents the type alias "openlist:plugin-driver/exports@0.1.0#capability".
//
// See [types.Capability] for more information.
type Capability = types.Capability

// Object represents the type alias "openlist:plugin-driver/exports@0.1.0#object".
//
// See [types.Object] for more information.
type Object = types.Object

// RangeSpec represents the exported type alias "openlist:plugin-driver/exports@0.1.0#range-spec".
//
// See [types.RangeSpec] for more information.
type RangeSpec = types.RangeSpec

// OutputStream represents the exported type alias "openlist:plugin-driver/exports@0.1.0#output-stream".
//
// See [types.OutputStream] for more information.
type OutputStream = types.OutputStream

// LinkArgs represents the exported type alias "openlist:plugin-driver/exports@0.1.0#link-args".
//
// See [types.LinkArgs] for more information.
type LinkArgs = types.LinkArgs

// LinkResult represents the exported type alias "openlist:plugin-driver/exports@0.1.0#link-result".
//
// See [types.LinkResult] for more information.
type LinkResult = types.LinkResult

// UploadRequest represents the exported type alias "openlist:plugin-driver/exports@0.1.0#upload-request".
//
// See [types.UploadRequest] for more information.
type UploadRequest = types.UploadRequest

// DriverErrors represents the type alias "openlist:plugin-driver/exports@0.1.0#driver-errors".
//
// See [types.DriverErrors] for more information.
type DriverErrors = types.DriverErrors

// Driver represents the exported resource "openlist:plugin-driver/exports@0.1.0#driver".
//
// --- 生命周期与元数据 ---
//
//	resource driver
type Driver cm.Resource

// DriverResourceNew represents the imported resource-new for resource "driver".
//
// Creates a new resource handle.
//
//go:nosplit
func DriverResourceNew(rep cm.Rep) (result Driver) {
	rep0 := cm.Reinterpret[uint32](rep)
	result0 := wasmimport_DriverResourceNew((uint32)(rep0))
	result = cm.Reinterpret[Driver]((uint32)(result0))
	return
}

// ResourceRep represents the imported resource-rep for resource "driver".
//
// Returns the underlying resource representation.
//
//go:nosplit
func (self Driver) ResourceRep() (result cm.Rep) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_DriverResourceRep((uint32)(self0))
	result = cm.Reinterpret[cm.Rep]((uint32)(result0))
	return
}

// ResourceDrop represents the imported resource-drop for resource "driver".
//
// Drops a resource handle.
//
//go:nosplit
func (self Driver) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_DriverResourceDrop((uint32)(self0))
	return
}

func init() {
	Exports.Driver.Destructor = func(self cm.Rep) {}
}

// wasmexport_DriverCopyFile_params represents the flattened function params for [wasmexport_DriverCopyFile].
// See the Canonical ABI flattening rules for more information.
type wasmexport_DriverCopyFile_params struct {
	_     cm.HostLayout `json:"-"`
	self  cm.Rep        `json:"self"`
	ctx   cm.Rep        `json:"ctx"`
	file  Object        `json:"file"`
	toDir Object        `json:"to-dir"`
}

// wasmexport_DriverLinkFile_params represents the flattened function params for [wasmexport_DriverLinkFile].
// See the Canonical ABI flattening rules for more information.
type wasmexport_DriverLinkFile_params struct {
	_    cm.HostLayout `json:"-"`
	self cm.Rep        `json:"self"`
	ctx  cm.Rep        `json:"ctx"`
	file Object        `json:"file"`
	args LinkArgs      `json:"args"`
}

// wasmexport_DriverLinkRange_params represents the flattened function params for [wasmexport_DriverLinkRange].
// See the Canonical ABI flattening rules for more information.
type wasmexport_DriverLinkRange_params struct {
	_      cm.HostLayout `json:"-"`
	self   cm.Rep        `json:"self"`
	ctx    cm.Rep        `json:"ctx"`
	file   Object        `json:"file"`
	args   LinkArgs      `json:"args"`
	range_ RangeSpec     `json:"range"`
}

// wasmexport_DriverListFiles_params represents the flattened function params for [wasmexport_DriverListFiles].
// See the Canonical ABI flattening rules for more information.
type wasmexport_DriverListFiles_params struct {
	_    cm.HostLayout `json:"-"`
	self cm.Rep        `json:"self"`
	ctx  cm.Rep        `json:"ctx"`
	dir  Object        `json:"dir"`
}

// wasmexport_DriverMakeDir_params represents the flattened function params for [wasmexport_DriverMakeDir].
// See the Canonical ABI flattening rules for more information.
type wasmexport_DriverMakeDir_params struct {
	_    cm.HostLayout `json:"-"`
	self cm.Rep        `json:"self"`
	ctx  cm.Rep        `json:"ctx"`
	dir  Object        `json:"dir"`
	name string        `json:"name"`
}

// wasmexport_DriverMoveFile_params represents the flattened function params for [wasmexport_DriverMoveFile].
// See the Canonical ABI flattening rules for more information.
type wasmexport_DriverMoveFile_params struct {
	_     cm.HostLayout `json:"-"`
	self  cm.Rep        `json:"self"`
	ctx   cm.Rep        `json:"ctx"`
	file  Object        `json:"file"`
	toDir Object        `json:"to-dir"`
}

// wasmexport_DriverRemoveFile_params represents the flattened function params for [wasmexport_DriverRemoveFile].
// See the Canonical ABI flattening rules for more information.
type wasmexport_DriverRemoveFile_params struct {
	_    cm.HostLayout `json:"-"`
	self cm.Rep        `json:"self"`
	ctx  cm.Rep        `json:"ctx"`
	file Object        `json:"file"`
}

// wasmexport_DriverRenameFile_params represents the flattened function params for [wasmexport_DriverRenameFile].
// See the Canonical ABI flattening rules for more information.
type wasmexport_DriverRenameFile_params struct {
	_       cm.HostLayout `json:"-"`
	self    cm.Rep        `json:"self"`
	ctx     cm.Rep        `json:"ctx"`
	file    Object        `json:"file"`
	newName string        `json:"new-name"`
}

// wasmexport_DriverUploadFile_params represents the flattened function params for [wasmexport_DriverUploadFile].
// See the Canonical ABI flattening rules for more information.
type wasmexport_DriverUploadFile_params struct {
	_    cm.HostLayout `json:"-"`
	self cm.Rep        `json:"self"`
	ctx  cm.Rep        `json:"ctx"`
	dir  Object        `json:"dir"`
	req  UploadRequest `json:"req"`
}
