// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package exports represents the exported interface "openlist:plugin-driver/exports@0.1.0".
//
// -----------------------------
// 驱动（Driver）接口
// -----------------------------
// 所有驱动插件必须实现并导出的核心接口。
// 所有 ctx 使用 borrow<cancellable> 由host端管理生命周期
package exports

import (
	"github.com/OpenListTeam/openlist-wasi-plugin-driver/binding/openlist/plugin-driver/types"
	"go.bytecodealliance.org/cm"
)

// Cancellable represents the exported type alias "openlist:plugin-driver/exports@0.1.0#cancellable".
//
// See [types.Cancellable] for more information.
type Cancellable = types.Cancellable

// DriverProps represents the type alias "openlist:plugin-driver/exports@0.1.0#driver-props".
//
// See [types.DriverProps] for more information.
type DriverProps = types.DriverProps

// FormField represents the type alias "openlist:plugin-driver/exports@0.1.0#form-field".
//
// See [types.FormField] for more information.
type FormField = types.FormField

// Capability represents the type alias "openlist:plugin-driver/exports@0.1.0#capability".
//
// See [types.Capability] for more information.
type Capability = types.Capability

// Object represents the type alias "openlist:plugin-driver/exports@0.1.0#object".
//
// See [types.Object] for more information.
type Object = types.Object

// RangeSpec represents the exported type alias "openlist:plugin-driver/exports@0.1.0#range-spec".
//
// See [types.RangeSpec] for more information.
type RangeSpec = types.RangeSpec

// OutputStream represents the exported type alias "openlist:plugin-driver/exports@0.1.0#output-stream".
//
// See [types.OutputStream] for more information.
type OutputStream = types.OutputStream

// LinkArgs represents the exported type alias "openlist:plugin-driver/exports@0.1.0#link-args".
//
// See [types.LinkArgs] for more information.
type LinkArgs = types.LinkArgs

// LinkResult represents the exported type alias "openlist:plugin-driver/exports@0.1.0#link-result".
//
// See [types.LinkResult] for more information.
type LinkResult = types.LinkResult

// UploadRequest represents the exported type alias "openlist:plugin-driver/exports@0.1.0#upload-request".
//
// See [types.UploadRequest] for more information.
type UploadRequest = types.UploadRequest

// DriverErrors represents the type alias "openlist:plugin-driver/exports@0.1.0#driver-errors".
//
// See [types.DriverErrors] for more information.
type DriverErrors = types.DriverErrors

// wasmexport_ListFiles_params represents the flattened function params for [wasmexport_ListFiles].
// See the Canonical ABI flattening rules for more information.
type wasmexport_ListFiles_params struct {
	_   cm.HostLayout `json:"-"`
	ctx cm.Rep        `json:"ctx"`
	dir Object        `json:"dir"`
}

// wasmexport_LinkFile_params represents the flattened function params for [wasmexport_LinkFile].
// See the Canonical ABI flattening rules for more information.
type wasmexport_LinkFile_params struct {
	_    cm.HostLayout `json:"-"`
	ctx  cm.Rep        `json:"ctx"`
	file Object        `json:"file"`
	args LinkArgs      `json:"args"`
}

// wasmexport_LinkRange_params represents the flattened function params for [wasmexport_LinkRange].
// See the Canonical ABI flattening rules for more information.
type wasmexport_LinkRange_params struct {
	_      cm.HostLayout `json:"-"`
	ctx    cm.Rep        `json:"ctx"`
	file   Object        `json:"file"`
	args   LinkArgs      `json:"args"`
	range_ RangeSpec     `json:"range"`
}

// wasmexport_MakeDir_params represents the flattened function params for [wasmexport_MakeDir].
// See the Canonical ABI flattening rules for more information.
type wasmexport_MakeDir_params struct {
	_    cm.HostLayout `json:"-"`
	ctx  cm.Rep        `json:"ctx"`
	dir  Object        `json:"dir"`
	name string        `json:"name"`
}

// wasmexport_RenameFile_params represents the flattened function params for [wasmexport_RenameFile].
// See the Canonical ABI flattening rules for more information.
type wasmexport_RenameFile_params struct {
	_       cm.HostLayout `json:"-"`
	ctx     cm.Rep        `json:"ctx"`
	file    Object        `json:"file"`
	newName string        `json:"new-name"`
}

// wasmexport_MoveFile_params represents the flattened function params for [wasmexport_MoveFile].
// See the Canonical ABI flattening rules for more information.
type wasmexport_MoveFile_params struct {
	_     cm.HostLayout `json:"-"`
	ctx   cm.Rep        `json:"ctx"`
	file  Object        `json:"file"`
	toDir Object        `json:"to-dir"`
}

// wasmexport_RemoveFile_params represents the flattened function params for [wasmexport_RemoveFile].
// See the Canonical ABI flattening rules for more information.
type wasmexport_RemoveFile_params struct {
	_    cm.HostLayout `json:"-"`
	ctx  cm.Rep        `json:"ctx"`
	file Object        `json:"file"`
}

// wasmexport_CopyFile_params represents the flattened function params for [wasmexport_CopyFile].
// See the Canonical ABI flattening rules for more information.
type wasmexport_CopyFile_params struct {
	_     cm.HostLayout `json:"-"`
	ctx   cm.Rep        `json:"ctx"`
	file  Object        `json:"file"`
	toDir Object        `json:"to-dir"`
}

// wasmexport_UploadFile_params represents the flattened function params for [wasmexport_UploadFile].
// See the Canonical ABI flattening rules for more information.
type wasmexport_UploadFile_params struct {
	_   cm.HostLayout `json:"-"`
	ctx cm.Rep        `json:"ctx"`
	dir Object        `json:"dir"`
	req UploadRequest `json:"req"`
}
