// Code generated by wit-bindgen-go. DO NOT EDIT.

package exports

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "openlist:plugin-driver@0.1.0".

//go:wasmexport openlist:plugin-driver/exports@0.1.0#set-handle
//export openlist:plugin-driver/exports@0.1.0#set-handle
func wasmexport_SetHandle(handle0 uint32) {
	handle := (uint32)((uint32)(handle0))
	Exports.SetHandle(handle)
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#get-properties
//export openlist:plugin-driver/exports@0.1.0#get-properties
func wasmexport_GetProperties() (result *DriverProps) {
	result_ := Exports.GetProperties()
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#get-form-meta
//export openlist:plugin-driver/exports@0.1.0#get-form-meta
func wasmexport_GetFormMeta() (result *cm.List[FormField]) {
	result_ := Exports.GetFormMeta()
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#init
//export openlist:plugin-driver/exports@0.1.0#init
func wasmexport_Init(ctx0 uint32) (result *cm.Result[DriverErrors, struct{}, DriverErrors]) {
	ctx := cm.Reinterpret[cm.Rep]((uint32)(ctx0))
	result_ := Exports.Init(ctx)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#drop
//export openlist:plugin-driver/exports@0.1.0#drop
func wasmexport_Drop(ctx0 uint32) (result *cm.Result[DriverErrors, struct{}, DriverErrors]) {
	ctx := cm.Reinterpret[cm.Rep]((uint32)(ctx0))
	result_ := Exports.Drop(ctx)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#get-file
//export openlist:plugin-driver/exports@0.1.0#get-file
func wasmexport_GetFile(ctx0 uint32, path0 *uint8, path1 uint32) (result *cm.Result[ObjectShape, Object, DriverErrors]) {
	ctx := cm.Reinterpret[cm.Rep]((uint32)(ctx0))
	path := cm.LiftString[string]((*uint8)(path0), (uint32)(path1))
	result_ := Exports.GetFile(ctx, path)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#get-root
//export openlist:plugin-driver/exports@0.1.0#get-root
func wasmexport_GetRoot(ctx0 uint32) (result *cm.Result[ObjectShape, Object, DriverErrors]) {
	ctx := cm.Reinterpret[cm.Rep]((uint32)(ctx0))
	result_ := Exports.GetRoot(ctx)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#list-files
//export openlist:plugin-driver/exports@0.1.0#list-files
func wasmexport_ListFiles(params *wasmexport_ListFiles_params) (result *cm.Result[DriverErrorsShape, cm.List[Object], DriverErrors]) {
	result_ := Exports.ListFiles(params.ctx, params.dir)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#link-file
//export openlist:plugin-driver/exports@0.1.0#link-file
func wasmexport_LinkFile(params *wasmexport_LinkFile_params) (result *cm.Result[LinkResultShape, LinkResult, DriverErrors]) {
	result_ := Exports.LinkFile(params.ctx, params.file, params.args)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#link-range
//export openlist:plugin-driver/exports@0.1.0#link-range
func wasmexport_LinkRange(params *wasmexport_LinkRange_params) (result *cm.Result[DriverErrors, struct{}, DriverErrors]) {
	result_ := Exports.LinkRange(params.ctx, params.file, params.args, params.range_)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#make-dir
//export openlist:plugin-driver/exports@0.1.0#make-dir
func wasmexport_MakeDir(params *wasmexport_MakeDir_params) (result *cm.Result[OptionObjectShape, cm.Option[Object], DriverErrors]) {
	result_ := Exports.MakeDir(params.ctx, params.dir, params.name)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#rename-file
//export openlist:plugin-driver/exports@0.1.0#rename-file
func wasmexport_RenameFile(params *wasmexport_RenameFile_params) (result *cm.Result[OptionObjectShape, cm.Option[Object], DriverErrors]) {
	result_ := Exports.RenameFile(params.ctx, params.file, params.newName)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#move-file
//export openlist:plugin-driver/exports@0.1.0#move-file
func wasmexport_MoveFile(params *wasmexport_MoveFile_params) (result *cm.Result[OptionObjectShape, cm.Option[Object], DriverErrors]) {
	result_ := Exports.MoveFile(params.ctx, params.file, params.toDir)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#remove-file
//export openlist:plugin-driver/exports@0.1.0#remove-file
func wasmexport_RemoveFile(params *wasmexport_RemoveFile_params) (result *cm.Result[DriverErrors, struct{}, DriverErrors]) {
	result_ := Exports.RemoveFile(params.ctx, params.file)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#copy-file
//export openlist:plugin-driver/exports@0.1.0#copy-file
func wasmexport_CopyFile(params *wasmexport_CopyFile_params) (result *cm.Result[OptionObjectShape, cm.Option[Object], DriverErrors]) {
	result_ := Exports.CopyFile(params.ctx, params.file, params.toDir)
	result = &result_
	return
}

//go:wasmexport openlist:plugin-driver/exports@0.1.0#upload-file
//export openlist:plugin-driver/exports@0.1.0#upload-file
func wasmexport_UploadFile(params *wasmexport_UploadFile_params) (result *cm.Result[OptionObjectShape, cm.Option[Object], DriverErrors]) {
	result_ := Exports.UploadFile(params.ctx, params.dir, params.req)
	result = &result_
	return
}
